# COURSEWORK SPECIFICATION

## ECM1416 - Computational Mathematics

**Module Lecturers:** Dr Tinkle Chugh, Dr Gaojie (Jay) Jin, Dr Zhixuan Yang

**Academic Year:** 2025/26

**Title:** Vector, Matrix and Linear Equations

**Submission deadline:** 17th Feb 2026, 11:59am.

This assessment contributes **30%** of the total module mark.

**This is an individual assessment** and you are reminded of the University's regulations on collaboration and plagiarism. You must avoid plagiarism, collusion, and any academic misconduct behaviours. Further details about academic honesty and plagiarism can be found at https://ele.exeter.ac.uk/course/view.php?id=1957.

**Generative AI** :
This assessment has been categorised as {\bf AI-Assisted}. You can find further information in the University's policies around using AI in assessed work: https://www.exeter.ac.uk/students/infopoints/yourinfopointservices/assessments/ .

*Permitted use of AI in the assessment:*
1. To develop ideas
2. To assist with research or information gathering
3. To help you understand key concepts and theories
4. To identify trends and themes as part of data analysis
5. To provide feedback on a draft
6. To improve the plan or structure of my assessment
7. To identify trends and themes as part of data analysis
8. To generate images, figures or diagrams
9. To proofread and correct spelling or grammar errors
10. To format citations or references
11. OTHER (please state)

*When submitting your assessment, you must:*

1. Treat the AI tool like a citation from any other source.
3. Include a list of all AI prompts and hyperlinks to their output with your references, at the end of your work. You do not need to include the outputs themselves, just the links.
4. Retain the full outputs generated by the prompts you have used during your assignment. These outputs should be accessible at the hyperlinks which you have submitted with your assignment. You may be asked to produce this material in the event of an academic conduct inquiry.

__________________________

# What to submit

Please do all your work in this Jupyter notebook. Make a separate cell for every few lines of code, and use separate cells for text, like this one.
Save your file in the format `ECM1416_STUDENTNUMBER.ipynb` and zip it.
For example, if your student number is 12345678, save your coursework as `ECM1416_12345678.ipynb`.
Once you have done that, zip the file, producing a file called `ECM1416_12345678.zip`. This is the file you will have to upload and submit to ELE.

## Exercise 1 — Matrix Operations (15%)

**Questions**

(a) Compute the product of matrices. Show the process of multiplication. Print the results. (5%)

```python
A = np.array([[2,3],[-1,4]])
B = np.array([[5,-2],[0,3]])
```

(b) Verify using NumPy and show both `A @ B` and `B @ A`. Print the results. (5%)

(c) Using matrices A and B, define a new vector v, provide one example that ABv = BAv, and one example that ABv != BAv. Print the results of ABv and BAv. (5%)



In [1]:
# Answer 1: compute product and discuss
import numpy as np
A = np.array([[2,3],
              [-1,4]])
B = np.array([[5,-2],
              [0,3]])

# (a) Compute the product of matrices. Show the process of multiplication. Print the results. (5%)
# Variable name format = AB_rowcolumn
AB_11 = (A[0,0] * B[0,0]) + (A[0,1] * B[1,0])
AB_12 = (A[0,0] * B[0,1]) + (A[0,1] * B[1,1])
AB_21 = (A[1,0] * B[0,0]) + (A[1,1] * B[1,0])
AB_22 = (A[1,0] * B[0,1]) + (A[1,1] * B[1,1])
AB = np.array([[AB_11, AB_12],
               [AB_21, AB_22]])

print("\nFinal matrix A @ B =\n", AB)


# (b) Verify using NumPy and show both `A @ B` and `B @ A`. Print the results. (5%)
prod_AB = A @ B
prod_BA = B @ A

print('\nNumpy A @ B:\n', prod_AB)
print('\nNumpy B @ A:\n', prod_BA)



# (c) Using matrices A and B, define a new vector v, provide one example that ABv = BAv, and one example that ABv != BAv. Print the results of ABv and BAv. (5%)
v_equal = np.transpose(np.array([0,0]))
ABv_equal = prod_AB @ v_equal
BAv_equal = prod_BA @ v_equal

print("\n=== Example where ABv = BAv ===")
print("v_equal =", v_equal)
print("AB v_equal =", ABv_equal)
print("BA v_equal =", BAv_equal)

v_neq = np.transpose(np.array([3,0]))
ABv_neq = prod_AB @ v_neq
BAv_neq = prod_BA @ v_neq

print("\n=== Example where ABv != BAv ===")
print("v_neq =", v_neq)
print("AB v_neq =", ABv_neq)
print("BA v_neq =", BAv_neq)




Final matrix A @ B =
 [[10  5]
 [-5 14]]

Numpy A @ B:
 [[10  5]
 [-5 14]]

Numpy B @ A:
 [[12  7]
 [-3 12]]

=== Example where ABv = BAv ===
v_equal = [0 0]
AB v_equal = [0 0]
BA v_equal = [0 0]

=== Example where ABv != BAv ===
v_neq = [3 0]
AB v_neq = [ 30 -15]
BA v_neq = [36 -9]


## Exercise 2 — Solving Linear Systems (20%)

**Questions**

Consider the following system of linear equations: Ax=b, where A and b are defined in the coding cell.

You must not use numpy.linalg.solve, numpy.linalg.inv, or any external library function that performs matrix inversion or Gaussian elimination.

(a) Solve the system using Gaussian elimination, implemented entirely by your own code. (10%)

(b) Solve the system by computing the matrix inverse manually using your own implementation, and then compute x=A^−1 b. (5%)

(c) Measure and compare the running time and judge which method is more efficient. (5%)



In [30]:
from time import time

# Answer 2: Solving Linear Systems 
A = np.array([[12, -5,  3, -2],
              [-4, 15, -6,  7],
              [ 5, -3, 18, -9],
              [-2,  4, -8, 20]], dtype=float)

b = np.array([3, 7, 5, 9], dtype=float)

# You must not use numpy.linalg.solve, numpy.linalg.inv, or any external library function that performs matrix inversion or Gaussian elimination.
# (a) Solve the system using Gaussian elimination, implemented entirely by your own code. (10%)

# Start the timer
ge_start_timer = time()

# Augment matrix A with vector b
Ab_aug = np.ndarray((4,5))
# Glue vector b onto the right hand side of A
for i in range(4):
    Ab_aug[i] = np.append(A[i], b[i])

# Element A_11 is first pivot value
# R2 = R2 + (1/3)R1
Ab_aug[1] = Ab_aug[1] + (Ab_aug[0] / 3)
# R3 = R3 - (5/12)R1
Ab_aug[2] = Ab_aug[2] - ((5 * Ab_aug[0]) / 12)
# R4 = R4 + (1/6)R1
Ab_aug[3] = Ab_aug[3] + (Ab_aug[0] / 6)

# Element A_22 is next pivot value
# R3 = R3 + (A_32/A_22)R2
Ab_aug[2] = Ab_aug[2] - ((Ab_aug[2][1] * Ab_aug[1]) / Ab_aug[1][1])
# R4 = R4 - (A_42/A_22)R2
Ab_aug[3] = Ab_aug[3] - ((Ab_aug[3][1] * Ab_aug[1]) / Ab_aug[1][1])

# Element A_33 is the third pivot value
# R4 = R4 - (A_43/A_33)R3
Ab_aug[3] = Ab_aug[3] - ((Ab_aug[3][2] * Ab_aug[2]) / Ab_aug[2][2])

# A is now in Row Echelon Form (Upper-Triangular)!!

# Start backward substitution
x_4 = Ab_aug[3][4] / Ab_aug[3][3]
x_3 = (Ab_aug[2][4] - (Ab_aug[2][3] * x_4)) / Ab_aug[2][2]
x_2 = (Ab_aug[1][4] - (Ab_aug[1][3] * x_4) - (Ab_aug[1][2] * x_3)) / Ab_aug[1][1]
x_1 = (Ab_aug[0][4] - (Ab_aug[0][3] * x_4) - (Ab_aug[0][2] * x_3) - (Ab_aug[0][1] * x_2)) / Ab_aug[0][0]

# End the timer
ge_end_timer = time()

x_ge = np.transpose(np.array([x_1, x_2, x_3, x_4]))
print("Solution x (Gaussian elimination):")
print(x_ge)



# (b) Solve the system by computing the matrix inverse manually using your own implementation, and then compute x=A^−1 b. (5%)

def calc_minor(matrix: np.array, row: int, column: int) -> np.array:
    """
    This function calculates the minor of a given element, at position matrix_rowcolumn.
    
    Parameters:
     - row is 1 based
     - column is 1 based
    """

    # Convert row and column to 0-based
    row -= 1
    column -= 1

    # If matrix is 2x2, return single element
    if (len(matrix) == 2):
        return matrix[1][column+1]

    # Initialise the numpy array to hold the new matrix with the required row removed
    new_matrix_1 = []

    # Loop through each row and remove the required row
    for i in range(len(matrix)):
        if i != row:
            new_matrix_1.append(matrix[i])

    # Convert back to a numpy array
    new_matrix_1 = np.array(new_matrix_1)

    # Initialise a list to hold all elements with the required column removed
    element_list = []

    # Loop through each row
    for i in range(len(new_matrix_1)):
        # Loop through each column
        for j in range(len(new_matrix_1[0])):
            if j != column:
                element_list.append(new_matrix_1[i][j])
    
    # Convert to a np array and change the shape
    new_matrix_2 = np.array(element_list).reshape((len(new_matrix_1), len(new_matrix_1)))

    return new_matrix_2

def calc_determinant(matrix: np.array) -> int:
    """This is a recursive function that calculates the determinant for any size square matrix."""

    # Ensure the matrix is square
    if (len(matrix) != len(matrix[0])): raise ValueError(f"Matrix is not square. {len(matrix)} is not {len(matrix[0])}.")

    # If the matrix is 2x2, return the determinant
    if (len(matrix) == 2):
        return (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])

    # Recursive section
    # Initialise the determinant
    determinant = 0

    # Use Lapace's Formula to calculate the determinant
    for column in range(len(matrix[0])):
        determinant += ((-1) ** (1 + column + 1)) * (matrix[0][column]) * (calc_determinant(calc_minor(matrix, 1, column + 1)))
    
    return determinant

# Start the timer
inv_start_timer = time()

# Use the above functions to calculate the determinant of matrix A
det_A = calc_determinant(A)

# Copy matrix A and then calculate the matrix of minors
matrix_of_minors = np.copy(A)

# Iterate through each element in A and calculate the minor for each
# At the same time, apply the sign net to calculate the matrix of cofactors
for row in range(len(matrix_of_minors)):
    for column in range(len(matrix_of_minors)):
        matrix_of_minors[row][column] = ((-1) ** (row + column)) * calc_determinant(calc_minor(A, row+1, column+1))

# Transpose the matrix of minors
matrix_of_minors_t = np.copy(matrix_of_minors)
for row in range(len(matrix_of_minors)):
    for column in range(len(matrix_of_minors)):
        temp = matrix_of_minors[column][row]
        matrix_of_minors_t[column][row] = matrix_of_minors[row][column]
        matrix_of_minors_t[row][column] = temp

# Divide the transpose of the matrix of cofactors by the determinant
A_inv = matrix_of_minors_t / det_A

# Multiply b by A^-1
x_inv = A_inv @ b

# End the timer
inv_end_timer = time()

print("\nSolution x (via A^{-1} b):")
print(x_inv)



# (c) Measure and compare the average running time and judge which method is more efficient. (5%)
t_ge = ge_end_timer - ge_start_timer
t_inv = inv_end_timer - inv_start_timer

print()
print(f"Average time (Gaussian elimination): {t_ge:.6e} seconds")
print(f"Average time (inverse):  {t_inv:.6e} seconds\n")

#Input (Gaussian elimination) or (Inverse method)
method = 'Gaussian elimination' if t_ge < t_inv else 'Inverse method'
print(method + " is more efficient.")


Solution x (Gaussian elimination):
[0.42946724 0.51652955 0.54923748 0.60933581]

Solution x (via A^{-1} b):
[0.42946724 0.51652955 0.54923748 0.60933581]

Average time (Gaussian elimination): 5.347729e-04 seconds
Average time (inverse):  2.101421e-03 seconds

Gaussian elimination is more efficient.


## Exercise 3 — Vector Spaces and Orthogonality (15%)

**Questions**

(a) Given vectors `u = [1, 2, 3]` and `v = [3, -6, 3]`, check orthogonality and construct unit vectors `e_1, e_2` in the directions of `u, v`. (5%)

(b) Compute the projection of `u` onto `v`. (5%)

(c) Provide an example of vector `z` which is orthogonal to both `u` and `v`. (5%)



In [57]:
from math import sqrt

# Answer 3: Vector Spaces and Orthogonality
# Given vectors
u = np.array([1.0, 2.0, 3.0])
v = np.array([3.0, -6.0, 3.0])

# (a) Given vectors `u = [1, 2, 3]` and `v = [3, -6, 3]`, check orthogonality and construct unit vectors `e_1, e_2` in the directions of `u, v`. (5%)

# If the dot product is:
#  - positive = vectors are pointing in the same direction
#  - zero = the vectors are orthogonal (perpendicular)
#  - negative = the vectors are pointing in opposite directions

# Calc the dot product
dot_uv = 0
for i in range(len(u)):
    dot_uv += (u[i] * v[i])

print("Dot product u·v =", dot_uv)

# Input "orthogonal" or "NOT orthogonal"
print(f"Therefore, u and v are {"orthogonal" if dot_uv == 0 else "not orthogonal"}")

# To normalise a vector, divide each component by the length of the vector
def normalise(vector: np.array) -> np.array:
    # Calculate the length of the vector
    magnitude = 0
    for i in range(len(vector)):
        magnitude += (vector[i] ** 2)
    magnitude = sqrt(magnitude)

    # Divide each element by the length
    return vector / magnitude

# Normalise u and v
e1 = normalise(u)
e2 = normalise(v)

# Output the normalise vectors
print("e1 =", e1)
print("e2 =", e2)



# (b) Compute the projection of `u` onto `v`. (5%)
# To project u onto v, we first calculate how much of vector u points in the direction of vector v
# This is done by calculating the dot product of u with the unit vector v
# This gives you a scaler number which you can multiply with the unit vector v, to get the vector projection of u onto v

# We have normalised v and stored the value in e2
# Calculate the dot product of u and unit v
dot_u_with_unit_v = 0

for i in range(len(u)):
    dot_u_with_unit_v += u[i] * e2[i]

# Now, multiply this scaler by the unit vector v
proj_u_on_v = dot_u_with_unit_v * e2

print("\nProjection of u onto v =", proj_u_on_v)
print("Since u and v are orthogonal, there is no projection of u onto v that\nresults in a vector with magnitude not equal to 0.")



# (c) Provide an example of vector `z` which is orthogonal to both `u` and `v`. (5%)
# This question utilises the cross product
# Construct a matrix with row 1 being the unit vectors i, j, k, row 2 being vector u
# and row 3 being vector v
cross_prod_mat = np.array([[1,1,1], u, v])

# Now, calculate the determinant of this constructed matrice's
# minors from the first row
# The middle element is multipled by -1 because of the cofactors
z_simple = np.array([calc_determinant(calc_minor(cross_prod_mat, 1, 1)),
                     (-1) * calc_determinant(calc_minor(cross_prod_mat, 1, 2)),
                     calc_determinant(calc_minor(cross_prod_mat, 1, 3))])

print("\nz =", z_simple)

# Verify orthogonality
print("z·u =", np.dot(z_simple, u))
print("z·v =", np.dot(z_simple, v))


Dot product u·v = 0.0
Therefore, u and v are orthogonal
e1 = [0.26726124 0.53452248 0.80178373]
e2 = [ 0.40824829 -0.81649658  0.40824829]

Projection of u onto v = [ 0. -0.  0.]
Since u and v are orthogonal, there is no projection of u onto v that
results in a vector with magnitude not equal to 0.

z = [ 24.   6. -12.]
z·u = 0.0
z·v = 0.0


## Exercise 4 — Advanced Matrix Operations (20%)

**Questions**
Note: You must not use numpy.linalg.solve, numpy.linalg.inv, numpy.linalg.det, or any external library function that performs matrix operations.

Consider the block matrices:

\[
M = 
\begin{bmatrix}
A & I \\
0 & B
\end{bmatrix},
N = 
\begin{bmatrix}
B & -I \\
0 & A
\end{bmatrix},
\]


(a)
```python
A = np.array([[2, 3], 
              [-1, 4]])

B = np.array([[5, -2], 
              [0, 3]])

I = np.eye(2)
```
Determine whether M is invertible. (10%)

(b) Investigate whether there exist matrices A and B such that MN-NM = NM-MN, if so, provide one example of A and B, and verify your result in code. (10%)



In [ ]:
# Answer 4: Advanced Matrix Operations
A = np.array([[2, 3],
              [-1, 4]])

B = np.array([[5, -2],
              [0,  3]])

I = np.eye(2)

# Construct block matrices M and N
M = np.block([[A, I],
              [np.zeros((2,2)), B]])

N = np.block([[B, -I],
              [np.zeros((2,2)), A]])

# Note: You must not use numpy.linalg.solve, numpy.linalg.inv, numpy.linalg.det, or any external library function that performs matrix operations.
# (a) Determine whether M is invertible, show the code. (10%)



# Input "M is invertible" or "M is not invertible"
print("M is ")



# (b) Investigate whether there exist matrices A and B such that MN-NM = NM-MN, if so, provide one example of A and B, and verify your result in code. (10%)


# Show examples of A and B
print("\nA=\n", A_ex)
print("\nB=\n", B_ex)
print("\nMN - NM =\n", diff1)
print("\nNM - MN =\n", diff2)

# Otherwise, print "No examples of A and B"
# print("No examples of A and B")







## Exercise 5 — Eigenvalues and Eigenvectors (10%)

**Questions**

Let
`A=`
`[[4 & 1 & 1]`
`[1 & 4 & 1]`
`[1 & 1 & 4]]`


Note: You must not use any external library function that performs eigen-operations directly.
(a) Compute eigenvalues and eigenvectors of `A`. (5%)

(b) Verify `A v = lambda v` for each eigenpair. (5%)



In [ ]:
# Answer 5: Eigenvalues and Eigenvectors
A = np.array([[4,1,1],
              [1,4,1],
              [1,1,4]], dtype=float)

# Note: You must not use any external library function that performs eigen-operations directly.  
# (a) Compute eigenvalues and eigenvectors of `A`. (5%)

print("\nEigenvalues:", eigvals)
print("\nEigenvectors (column per eigenvalue):\n", eigvecs)




# (b) Verify `A v = lambda v` for each eigenpair. (5%)

print("||A v - λ v|| =", )


## Exercise 6 — Taylor Series Approximation (10%)

**Questions**

Let `f(x) = exp(x) * sin(x)`. For `n = [1, 3, 5, 7, 9]`, `x∈[0.5,1.0]`, implement a function to compute the n-th order Taylor polynomial of `f(x)` centered at `x₀=0` without using symbolic computation libraries like sympy. For each order `n`, evaluate the Taylor polynomial at `x=0.5` and `x=1.0`. Print all computational results of Taylor polynomial.

Note: You must not use sympy or any symbolic differentiation library, but can use numpy. 



In [ ]:
# Answer 6: Taylor Series Approximation (10%)

def true_function(x):
    return np.exp(x) * np.sin(x)

orders = [1, 3, 5, 7, 9]
x_values = [0.5, 1.0]

def taylor_polynomial(x, n):
    

for x_eval in x_values:

    for n in orders:
        
        print(f"{n:<10} {taylor_val:<20.10f}")


## Exercise 7 — ODEs (10 %)

You must implement Euler’s method **from scratch** without using any numerical ODE solver libraries.

Consider the initial value problem (IVP):

$
\frac{dy}{dx} = x + y, \quad y(0) = 1
$

The exact solution is given as:
$y(x) = 2e^x - x - 1$

Answer the following questions.


(a) Write a Python program to implement Euler’s Method for the given ODE (5 %)

- Do NOT use any numerical ODE libraries (e.g., scipy, numpy ODE solvers)
- Use only basic Python constructs (loops, functions, arithmetic operations)

Use:
- Step size \( h = 0.1 \)
- Interval \( $0 \le x \le 1 $\)

(b) Repeat the computation using a smaller step size \( h = 0.05 \) and compare the errors obtained for \( h = 0.1 \) and \( h = 0.05 \). Explain briefly why decreasing the step size helps improve the accuracy.(5 % - 2 marks for computation and 3 for the comment on accuracy)



In [ ]:
# Answer 7: ODEs (10 %)

#(a) (5 %)
import math
def f(x, y):
    return x + y

def exact_solution(x):
    return 2 * math.exp(x) - x - 1


def euler_method(x0, y0, h, x_end):
    





# (b) (5%)
h_small = 0.05



# Comment on the accuracy here:

