# Week 4 workshop 

In [2]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

def gaussian_elimination(Ab, tol=1e-10):
    """Gauss–Jordan elimination."""
    R = Ab.astype(float).copy()
    m, n = R.shape
    r = 0
    for c in range(n-1):
        # choose pivot row
        pivot = None
        max_val = tol
        for rr in range(r, m):
            v = abs(R[rr, c])
            if v > max_val:
                max_val = v
                pivot = rr
        if pivot is None:
            continue
        if pivot != r:
            R[[r, pivot]] = R[[pivot, r]]
        # normalize pivot row
        pv = R[r, c]
        R[r, :] /= pv
        # eliminate other rows
        for rr in range(m):
            if rr == r:
                continue
            factor = R[rr, c]
            if abs(factor) > tol:
                R[rr, :] -= factor * R[r, :]
        r += 1
        if r == m:
            break
    R[np.abs(R) < tol] = 0.0
    return R

def ranks(A, b, tol=1e-10):
    """(rank(A), rank([A|b])) via SVD numerical rank."""
    sA = np.linalg.svd(A, compute_uv=False)
    rA = int(np.sum(sA > tol))
    Ab = np.column_stack([A, b])
    sAb = np.linalg.svd(Ab, compute_uv=False)
    rAb = int(np.sum(sAb > tol))
    return rA, rAb

def classify_system(A, b, tol=1e-10):
    """Classify Ax=b as unique / infinite / none."""
    m, n = A.shape
    rA, rAb = ranks(A, b, tol=tol)
    if rAb > rA:
        return "no solution"
    if rA == n:
        return "unique solution"
    return "infinitely many solutions"

## Exercise 1 — Solve a 2×2 system 

Solve:
\[
\begin{cases}
x + y = 5\\
2x - y = 1
\end{cases}
\]

**Task**
- Use `np.linalg.solve(A, b)` to compute \((x,y)\).


In [14]:
# EXERCISE 1
# Set up matrix A
A = np.array([[ 1, 1],
              [ 2,-1]])

# Set up vector b
b = np.array([5,1])

# Use np.linalg.solve() to compute v
x = np.linalg.solve(A,b)

# Output the calculation
print("1) Solve Ax = b\n")
print(f"A = \n{A}\n")
print(f"b = {b}\n")
print(f"x = {x}")

1) Solve Ax = b

A = 
[[ 1  1]
 [ 2 -1]]

b = [5 1]

x = [2. 3.]


## Exercise 2 — Solve an easy 3×3 system (unique solution)

Solve:
\[
\begin{cases}
x + y + z = 6\\
x + y = 4\\
x + z = 2
\end{cases}
\]

**Task**
- Build the matrix \(A\) and vector \(b\)
- Solve with `np.linalg.solve`


In [15]:
# EXERCISE 2

# General equation: Ax = b

# Construct matrix A
A = np.array([[ 1, 1, 1],
              [ 1, 1, 0],
              [ 1, 0, 1]])

# Construct vector b
b = np.array([6,4,2])

# Calculate x in the above equation
x = np.linalg.solve(A,b)

# Output the calculation
print("2) Solve Ax = b\n")
print(f"A = \n{A}\n")
print(f"b = {b}\n")
print(f"x = {x}")

2) Solve Ax = b

A = 
[[1 1 1]
 [1 1 0]
 [1 0 1]]

b = [6 4 2]

x = [0. 4. 2.]


## Exercise 3 — Using gaussian_elimination to solve the problem

\[
\begin{cases}
x + y + z = 6\\
x + y = 4\\
z = 2
\end{cases}
\]

**Task**
- Create the augmented matrix `[A|b]`
- Call `gaussian_elimination(Ab)`, print (x,y,z)


In [48]:
# EXERCISE 3
# Construct matrix A
A = np.array([[ 1, 1, 1],
              [ 1, 1, 0],
              [ 0, 0, 1]])

# Construct vector b
b = np.array([6,4,2])

# Construct the augmented matrix of A and b
Ab = np.ndarray((3,4))
for row in range(len(A)):
    Ab[row] = np.append(A[row],b[row])

# Solve using gaussian elimination
results = gaussian_elimination(Ab)

# Output the calculation
print("3) Solve Ax = b\n")
print(f"x={results[0,3]}\ny={results[1,3]}\nz={results[2,3]}")

3) Solve Ax = b

x=4.0
y=2.0
z=0.0


## Exercise 4 — Eigenvalues/eigenvectors 

Use NumPy to compute eigenvalues/eigenvectors for a diagonal matrix:
\[
D = [2 & 0\\ 0 & 5]
\]

**Task**
- Compute `w, V = np.linalg.eig(D)`
- Check that `D @ V[:,i] ≈ w[i] * V[:,i]`


In [56]:
# EXERCISE 5
# Construct matrix D
D = np.array([[ 2, 0],
              [ 0, 5]])

# Compute the eigenvalues and eigenvectors of D
e_vals, e_vectors = np.linalg.eig(D)

# Output question
print("4) Compute Eigenvalues and Eigenvectors\n")

# Iterate through each value/vector pair to check
for i in range(len(e_vals)):
    print(f"Pair {i+1}:\n  val = {e_vals[i]}\n  vector = {e_vectors[:,i]}\n  {D @ e_vectors[:,i]} \u2248 {e_vals[i] * e_vectors[:,i]}\n")

4) Compute Eigenvalues and Eigenvectors

Pair 1:
  val = 2.0
  vector = [1. 0.]
  [2. 0.] ≈ [2. 0.]

Pair 2:
  val = 5.0
  vector = [0. 1.]
  [0. 5.] ≈ [0. 5.]



## Exercise 5 — Quick check: eigenvalues of the inverse 

Let
\[
A = [2 & 0\\ 0 & 5]
\]

**Task**
- Compute `Ainv = np.linalg.inv(A)`
- Compare eigenvalues (A) and (A^{-1}).


In [61]:
# EXERCISE 6
# Construct matrix A
A = np.array([[ 2, 0],
              [ 0, 5]])

# Compute the inverse of matrix A from Q4
A_inv = np.linalg.inv(A)

# Compute the eigenvalues of A
e_vals = np.linalg.eigvals(A)

# Compute the eigenvalues of this inverse matrix
e_vals_inv = np.linalg.eigvals(A_inv)

print("5) Compare eigenvalues of A and A^{-1}\n")
# Compare the eigenvalues of A and A_inv
print(f"A's e_vals = {e_vals}")
print(f"A^{-1}'s e_vals = {e_vals}\n")
print("Therefore, the inverse matrix will always have the same eigenvalues as the original.")

5) Compare eigenvalues of A and A^{-1}

A's e_vals = [2. 5.]
A^-1's e_vals = [2. 5.]

Therefore, the inverse matrix will always have the same eigenvalues as the original.
