# Vectors & Matrices 

**Instructions**
- Use **NumPy** (and **SymPy** only when symbols are required).
- Write clear code and add short comments.
- Where asked for a “check”, print the value(s) that verify the claim.


In [1]:
import numpy as np
import sympy as sp

def vec(P, Q):
    P = np.array(P, dtype=float)
    Q = np.array(Q, dtype=float)
    return Q - P

def dist(P, Q):
    return np.linalg.norm(vec(P, Q))

def angle_deg(u, v):
    u = np.array(u, dtype=float)
    v = np.array(v, dtype=float)
    cos = (u @ v) / (np.linalg.norm(u) * np.linalg.norm(v))
    cos = np.clip(cos, -1.0, 1.0)
    return np.degrees(np.arccos(cos)), cos


## Part A — Vectors

### A1. Vector PQ and norm
For each pair \((P,Q)\), compute:
1) PQ = Q-P
2) ||PQ||

Pairs:
- (i) \(P=(-5,-7,2),\; Q=(-2,-3,4)\)
- (ii) \(P=(1,5,-3),\; Q=(2,3,4)\)
- (iii) \(P=(1,2,-3),\; Q=(0,0,0)\)

**Your code:**

In [7]:
# TODO: compute PQ and norm
p_vectors = np.array([[-5,-7,2], [1,5,-3], [1,2,-3]])
q_vectors = np.array([[-2,-3,4], [2,3,4], [0,0,0]])

for i in range(len(p_vectors)):
    print(f"{i+1})\n   P = {p_vectors[i]}\n   Q = {q_vectors[i]}")
    print(f"   Q-P = {vec(p_vectors[i], q_vectors[i])}")
    print(f"   ||PQ|| = {dist(p_vectors[i], q_vectors[i])}\n")

1)
   P = [-5 -7  2]
   Q = [-2 -3  4]
   Q-P = [3. 4. 2.]
   ||PQ|| = 5.385164807134504

2)
   P = [ 1  5 -3]
   Q = [2 3 4]
   Q-P = [ 1. -2.  7.]
   ||PQ|| = 7.3484692283495345

3)
   P = [ 1  2 -3]
   Q = [0 0 0]
   Q-P = [-1. -2.  3.]
   ||PQ|| = 3.7416573867739413



### A2. Angle between vectors
For each pair \((u,v)\), compute the angle (degrees) using dot products.

Pairs:
- (i) \(u=(1,1,1),\; v=(1,1,-1)\)
- (ii) \(u=(-1,0,4),\; v=(2,2,2)\)
- (iii) \(u=(2,2,1),\; v=(1,2,2)\)

**Your code:**

In [15]:
# TODO: compute angle (degrees) and cosine for each pair and print results
u_vectors = np.array([[1,1,1], [-1,0,4], [2,2,1]])
v_vectors = np.array([[1,1,-1], [2,2,2], [1,2,2]])

for i in range(len(u_vectors)):
    angle, cos = angle_deg(u_vectors[i], v_vectors[i])
    print(f"{i+1})\n    angle = {angle} degrees\n    cos = {cos}\n")

1)
    angle = 70.52877936550931 degrees
    cos = 0.33333333333333337

2)
    angle = 65.16010753498531 degrees
    cos = 0.420084025208403

3)
    angle = 27.266044450732828 degrees
    cos = 0.8888888888888888



### A3. Vector arithmetic, dot products, and angles
Let:
- \(a=(5,-6,4)\)
- \(b=(2,5,-3)\)
- \(c=(-1,0,4)\)

Compute:
1) (5a - 2b - 3c)  
2) AC+AB where (A=a,\;B=b,\;C=c )  
3) (a \dot b)  
4) the angle between (a) and (b) (degrees)  
5) ((4a-6b) \dot (2a+3c) )

**Your code:**

In [19]:
# TODO: compute (1)-(5) and print results in a readable way
a = np.array([5,-6,4])
b = np.array([2,5,-3])
c = np.array([-1,0,4])

# Q1: 5a - 2b - 3c
print(f"1) 5a - 2b - 3c = {(5*a) - (2*b) - (3*c)}\n")

# Q2: AC + AB
print(f"2) AC + AB = {vec(a,c) + vec(a,b)}\n")

# Q3: a DOT b
print(f"3) a DOT b = {(a[0]*b[0]) + (a[1]*b[1]) + (a[2]*b[2])}\n")

# Q4: Angle between a and b
angle, cos = angle_deg(a,b)
print(f"4) Angle between a and b = {angle} degrees\n")

# Q5: [d=](4a - 6b) DOT [e=](2a + 3c)
# d = [8,-54,34]
# e = [7,-12,20]
d = (4*a) - (6*b)
e = (2*a) + (3*c)
print(f"5) (4a - 6b) DOT (2a + 3c) = {(d[0]*e[0]) + (d[1]*e[1]) + (d[2]*e[2])}")

1) 5a - 2b - 3c = [ 24 -40  14]

2) AC + AB = [-9. 17. -7.]

3) a DOT b = -32

4) Angle between a and b = 126.2691457049313 degrees

5) (4a - 6b) DOT (2a + 3c) = 1384


## Part B — Matrices

### B1. Addition/Subtraction with shape checks
1) Compute \(A+B\) where:
A= [1&2&-2 \\ 3&0&2]
B= [4&0&-4 \\ -1&-3&-4].

2) Write a function `safe_add(A,B)` that either returns `A+B` or prints a helpful message when the shapes are incompatible.
3) Use `safe_add` to test these incompatible pairs:
- \(A\in R^{2\times 3}\), \(B\in R^{3\times 2}\)
- \(A\in R^{2\times 3}\), \(B\in R^{2\times 4}\)

**Your code:**

In [33]:
# TODO: implement the tasks in B1
# Set up the matrices
A = np.array([[ 1, 2,-2],
              [ 3, 0, 2]])
B = np.array([[ 4, 0,-4],
              [-1,-3,-4]])

# Q1: A + B
# Check whether A and B are additively conformable
# I.e. have the same number of rows and columns
if len(A) == len(B) and len(A[0]) == len(B[0]):
    print(f"1) A + B = \n{A + B}\n")

# Q2: write safe_add(A,B) to ensure A and B are additively conformable
def safe_add(A,B):
    # Check if A and B have the same shape
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        return A + B
    else:
        # Inform the user that they don't have the same shape
        print("3) A and B are not additively conformable.\n")
        return False;

# Q3: Test safe_add(A,B)
A = np.ones((2,3))
B = np.ones((3,2))
result = safe_add(A,B)
if type(result) != bool:
    print(f"3) a) A + B = {result}\n")

A = np.ones((2,3))
B = np.ones((2,4))
result = safe_add(A,B)
if type(result) != bool:
    print(f"3) b) A + B = {result}\n")

1) A + B = 
[[ 5  2 -6]
 [ 2 -3 -2]]

3) A and B are not additively conformable.

3) A and B are not additively conformable.



### B2. Matrix multiplication and shape rules
1) Compute (AB) for

A= [3&2&0 \\ -1&4&1]
B= [1&0 \\ 1&2 \\ 3&-1].

2) Compute (AB) for
A= [1&2 \\ 3&4]
B= [2&0&-3 \\ 1&-1&-2]

3) Explain (via Python error or a manual check) why (BA) is not defined for the matrices in (2).

**Your code:**

In [43]:
# TODO: compute the products; demonstrate why BA is not defined in (2)
# Q1: A @ B
A = np.array([[ 3, 2, 0],
              [-1, 4, 1]])
B = np.array([[ 1, 0],
              [ 1, 2],
              [ 3,-1]])
print(f"1) A @ B = \n{A @ B}\n")

# Q2: A @ B
A = np.array([[ 1, 2],
              [ 3, 4]])
B = np.array([[ 2, 0,-3],
              [ 1,-1,-2]])
print(f"2) A @ B = \n{A @ B}\n")

# Q3: Compute A @ B for A,B in Q2
print("3) For two matrices to be multiplicatively conformable, the number of columns in the first\n" \
      "   matrix must equal the number of rows in the second. Since matrix B has 3 columns and matrix\n" \
      "   A has 2 rows, they cannot be multiplied in this orientation.")
print(f"3) B @ A = \n{B @ A}\n")

1) A @ B = 
[[5 4]
 [6 7]]

2) A @ B = 
[[  4  -2  -7]
 [ 10  -4 -17]]

3) For two matrices to be multiplicatively conformable, the number of columns in the first
   matrix must equal the number of rows in the second. Since matrix B has 3 columns and matrix
   A has 2 rows, they cannot be multiplied in this orientation.


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### B3. Transpose identities (computational verification)
Using random integer matrices (choose any sizes that make sense):
1) Verify ((A+B)^T = A^T + B^T).  
2) Verify that (A^TA) and (AA^T) are symmetric.

**Your code:**

In [64]:
# TODO: generate random matrices and verify the identities
# Define matrix A and B with shape (2,3) and random values
A = np.array([[35, 4,16],
              [65,89,12]])
B = np.array([[34, 6,12],
              [ 5,73,42]])
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)

# Q1: (A + B)^T = A^T + B^T
print(f"A = \n{A}\n\nA^T = \n{A_transpose}\n\nB = \n{B}\n\nB^T = \n{B_transpose}\n")
print("\nQ1)")
print(f"A + B = \n{A + B}\n")
print(f"(A + B)^T = \n{np.transpose(A + B)}\n")
print(f"A^T + B^T = \n{np.transpose(A) + np.transpose(B)}\n")
print("Therefore, (A + B)^T = A^T + B^T, for any shaped matrix.")

# Q2: (A^T)A = A(A^T)
print("\n\nQ2)")
print(f"(A^T) @ A = \n{A_transpose @ A}\n")
print(f"((A^T) @ A)^T = \n{np.transpose(A_transpose @ A)}\n")
print(f"A @ (A^T) = \n{A @ A_transpose}\n")
print(f"(A @ (A^T))^T = \n{np.transpose(A @ A_transpose)}\n")
print("Since each calculated matrix is equal to its transpose, they are both symmetric.")

A = 
[[35  4 16]
 [65 89 12]]

A^T = 
[[35 65]
 [ 4 89]
 [16 12]]

B = 
[[34  6 12]
 [ 5 73 42]]

B^T = 
[[34  5]
 [ 6 73]
 [12 42]]


Q1)
A + B = 
[[ 69  10  28]
 [ 70 162  54]]

(A + B)^T = 
[[ 69  70]
 [ 10 162]
 [ 28  54]]

A^T + B^T = 
[[ 69  70]
 [ 10 162]
 [ 28  54]]

Therefore, (A + B)^T = A^T + B^T, for any shaped matrix.


Q2)
(A^T) @ A = 
[[5450 5925 1340]
 [5925 7937 1132]
 [1340 1132  400]]

((A^T) @ A)^T = 
[[5450 5925 1340]
 [5925 7937 1132]
 [1340 1132  400]]

A @ (A^T) = 
[[ 1497  2823]
 [ 2823 12290]]

(A @ (A^T))^T = 
[[ 1497  2823]
 [ 2823 12290]]

Since each calculated matrix is equal to its transpose, they are both symmetric.
