# ECM1416 Computational Mathematics (Term 2)
## Determinants and Inverses (Python/Jupyter)


In [20]:
import numpy as np
import sympy as sp

np.set_printoptions(suppress=True, precision=6)

def is_identity(M, tol=1e-9):
    M = np.array(M, dtype=float)
    n = M.shape[0]
    return np.linalg.norm(M - np.eye(n), ord=np.inf) <= tol


## Exercise 1 — 3×3 determinants (exact)

Compute the determinants of the following matrices **exactly** (as integers):
\[
A_1 = [ 3&-1&4\\ 2&0&5\\ 1&2&-2 ]
A_2 = [ 0&2&1\\ 1&-1&3\\ 2&1&4 ].
\]
1. Compute `det(A1)` and `det(A2)` using `sympy.Matrix(...).det()`.
2. Cross-check your answers numerically with `numpy.linalg.det` (you may see tiny floating error).


In [21]:
A1 = sp.Matrix([[3,-1,4],[2,0,5],[1,2,-2]])
A2 = sp.Matrix([[0,2,1],[1,-1,3],[2,1,4]])

# Print the determinants
print(f"1)\n  det(A1) = {A1.det()}\n  det(A2) = {A2.det()}")

1)
  det(A1) = -23
  det(A2) = 7


In [22]:
# Numerical cross-check (floating)
print(f"2)\n  det(A1) = {np.linalg.det(np.array(A1, dtype=float))}\n  det(A2) = {np.linalg.det(np.array(A2, dtype=float))}")

2)
  det(A1) = -23.0
  det(A2) = 6.999999999999999


## Exercise 2 — Determinant properties (row operations)

Let
\[
B = [ 1&2&0\\ 3&-1&4\\ 2&1&5 ].
\]
Create matrices obtained from **B** by each operation, and predict the new determinant from properties *before computing*:
1. Multiply **row 2** by k=-3 to get B_1.
2. Swap **row 1 and row 3** to get B_2.
3. Add 2 times row 1 to row 3 to get B_3.

For each, report `det(B)`, `det(B1)`, `det(B2)`, `det(B3)`, and check the predicted relationships.


In [23]:
B = sp.Matrix([[1,2,0],[3,-1,4],[2,1,5]])
print("Q1)")
print(f"  det(B) = {B.det()}")

B1 = B
B1[1] = B1[1] * (-3)
print(f"  det(B1) = {B1.det()}")

B2 = B
temp_row = B2[0]
B2[0] = B2[2]
B2[2] = temp_row
print(f"  det(B2) = {B2.det()}")

B3 = B
B3[2] = B3[2] + (2 * B3[0])
print(f"  det(B3) = {B3.det()}")

Q1)
  det(B) = -23
  det(B1) = 33
  det(B2) = 47
  det(B3) = 47


## Exercise 3 — Singular vs invertible

Consider
\[
C_1 = [ 2&1&3\\ 4&2&6\\ 1&0&1 ]
C_2 = [ 2&1&3\\ 4&2&7\\ 1&0&1 ].
\]
1. Compute the determinants and decide which matrix is singular.
2. For the invertible one, compute its inverse and verify it.


In [24]:
C1 = sp.Matrix([[2,1,3],[4,2,6],[1,0,1]])
C2 = sp.Matrix([[2,1,3],[4,2,7],[1,0,1]])

# Compute det(C1) and det(C2)
det_C1 = C1.det()
det_C2 = C2.det()

# Ouput the determinants
print(f"1)\n  det(C1) = {det_C1}\n  det(C2) = {det_C2}")
print("\n  Since the determinant of C1 is 0, it is singular and doesn't have an inverse.")

1)
  det(C1) = 0
  det(C2) = 1

  Since the determinant of C1 is 0, it is singular and doesn't have an inverse.


In [42]:
# Compute the inverse for C2
C2_inverse = np.linalg.inv(np.array(C2, dtype=float))
print(f"2)\n  C2^(-1) = \n{C2_inverse}")

# Verify the inverse
# If inverse, C2 * C2^-1 = I
C2_C2_inverse = np.array(C2 @ C2_inverse, dtype=int)
print(f"  C2 @ C2_inverse = \n{C2_C2_inverse}\n  I = \n{np.eye(3, dtype=int)}")
if np.eye(3, dtype=int).all() == C2_C2_inverse.all():
    print("C2_inverse is the correct inverse.")
else:
    print("C2_inverse is not the inverse.")

2)
  C2^(-1) = 
[[ 2. -1.  1.]
 [ 3. -1. -2.]
 [-2.  1. -0.]]
  C2 @ C2_inverse = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
  I = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
C2_inverse is the correct inverse.


## Exercise 4 — 2×2 inverses and verification

For each 2×2 matrix, compute the inverse **exactly** using `sympy` and verify:
\[
D_1=[ 4&7\\2&6 ]
D_2=[ 1&-3\\5&-15 ]
\]
Explain what happens for any non-invertible case.


In [26]:
D1 = sp.Matrix([[4,7],[2,6]])
D2 = sp.Matrix([[1,-3],[5,-15]])



In [52]:
# Inverses when determinant != 0
# Output the determinants
print(f"det(D1) = {D1.det()}\ndet(D2) = {D2.det()}")
print("Since det(D2) = 0, it is singular and eosn't have an inverse.\n")
# Ouput the matrices and inverse
print(f"D1^-1 = \n{np.array(D1, dtype=float)}")
print(f"D2^-1 = \n{np.array(D2, dtype=float)}")
print(f"D1^-1 = \n{np.array(D1.inv(), dtype=float)}")
#print(f"D2^-1 = \n{np.array(D2.inv(), dtype=float)}")

det(D1) = 10
det(D2) = 0
Since det(D2) = 0, it is singular and eosn't have an inverse.

D1^-1 = 
[[4. 7.]
 [2. 6.]]
D2^-1 = 
[[  1.  -3.]
 [  5. -15.]]
D1^-1 = 
[[ 0.6 -0.7]
 [-0.2  0.4]]


## Exercise 5 — 3×3 inverse and sanity checks

Let
\[
E= [ 1&1&2\\ 0&1&1\\ -2&0&1 ]
\]
1. Compute `det(E)`.
2. Compute `E^{-1}` exactly using `sympy`.
3. Verify `E*E^{-1} = I` (exactly).


In [28]:
E = sp.Matrix([[1,1,2],[0,1,1],[-2,0,1]])

In [66]:
print(f"1)\n  det(E) = {E.det()}")
E_inv = E.inv()
print(f"2)\n  E^-1 = \n{np.array(E_inv, dtype=int)}")

1)
  det(E) = 3
2)
  E^-1 = 
[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [67]:
# Exact verification
print(f"3)\n  E@E^-1 = \n{np.array(E@E_inv, dtype=int)}")
print(f"  Does E@E^-1 = I? {np.array(E@E_inv, dtype=int).all() == np.eye(3, dtype=int).all()}")


3)
  E@E^-1 = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
  Does E@E^-1 = I? True


## Exercise 6 — Solving a linear system with inverse vs solver

Solve the system Ax=b where
\[
A=[ 2&1&-1\\ 1&3&2\\ 3&1&1 ]
b=[ 2\\ 9\\ 7 ].
\]
1. Solve using `A.inv()*b` in `sympy` (exact rational solution).
2. Solve using `numpy.linalg.solve` (floating solution).
3. Confirm both solutions agree (within tolerance).


In [78]:
A = sp.Matrix([[2,1,-1],[1,3,2],[3,1,1]])
b = sp.Matrix([2,9,7])
x = np.array(A.inv() @ b, dtype=float)
print(f"1)\n  x = A^-1 * b = \n{x}")

1)
  x = A^-1 * b = 
[[1.266667]
 [1.333333]
 [1.866667]]


In [82]:
# Numpy solve (float)
A_np = np.array(A.tolist(), dtype=float)
b_np = np.array(b.tolist(), dtype=float).reshape(-1)
x_np = np.linalg.solve(A_np, b_np).reshape((3, 1))
print(f"2)\n  x_np = A_np^-1 * b_np = \n{x_np}")

2)
  x_np = A_np^-1 * b_np = 
[[1.266667]
 [1.333333]
 [1.866667]]


In [87]:
# Compare (tolerance)
c = x_np - x
print(f"3)  x_np - x = \n{c}")
print(f"  Are they within tolerance? {c.all() <= 1e-9}")

3)  x_np - x = 
[[ 0.]
 [ 0.]
 [-0.]]
  Are they within tolerance? True
